webtalk_init -webtalk_dir D:/Ondevice/system verilog/system_verilog/02.25_8bit_register_sv/02.25_8bit_register_sv.sim/sim_1/behav/xsim/xsim.dir/tb_fork_join_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 25 21:26:19 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5762a6cd-b6c3-44b1-afee-b53a244a0c9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "942ac83fc92b471383c02e985bed3690" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "11 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3133797751 -regid "" -xml D:/Ondevice/system verilog/system_verilog/02.25_8bit_register_sv/02.25_8bit_register_sv.sim/sim_1/behav/xsim/xsim.dir/tb_fork_join_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Ondevice/system verilog/system_verilog/02.25_8bit_register_sv/02.25_8bit_register_sv.sim/sim_1/behav/xsim/xsim.dir/tb_fork_join_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Ondevice/system verilog/system_verilog/02.25_8bit_register_sv/02.25_8bit_register_sv.sim/sim_1/behav/xsim/xsim.dir/tb_fork_join_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
